# Generated by Django 6.0.1 on 2026-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('student_phn_number', models.CharField(max_length=15)),
                ('parent_phn_number', models.CharField(max_length=15)),
                ('room_bed', models.CharField(blank=True)),
                ('joined_date', models.DateField(blank=True)),
                ('advance_amount', models.TextField(blank=True)),
                ('total_fee', models.TextField(blank=True)),
            ],
        ),
    ]
