# Generated by Django 6.0.1 on 2026-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='hostel_username_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='hostel_username_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='hostel_username_id',
            field=models.TextField(blank=True),
        ),
    ]
