# Generated by Django 6.0.1 on 2026-02-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bed_hostel_username_id_room_hostel_username_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='room_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.bed'),
        ),
    ]
