# Generated by Django 6.0.1 on 2026-02-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_details_room_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='room_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bed'),
        ),
    ]
