# Generated by Django 6.0.1 on 2026-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_details_room_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='room_bed',
            field=models.CharField(blank=True),
        ),
    ]
