# Generated by Django 6.0.1 on 2026-02-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_details_room_bed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='room_bed_data',
        ),
    ]
