# Generated by Django 6.0.1 on 2026-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_student_details_room_bed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='student_bed_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_room_number',
            field=models.TextField(blank=True),
        ),
    ]
