# Generated by Django 6.0.1 on 2026-02-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_student_details_student_bed_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='student_bed_number',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='student_room_number',
        ),
    ]
