# Generated by Django 6.0.1 on 2026-02-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_payment',
            name='nothing',
            field=models.TextField(blank=True),
        ),
    ]
