# Generated by Django 6.0.1 on 2026-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_student_payment_nothing'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_payment_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_username_id', models.TextField(blank=True)),
                ('student_id', models.TextField(blank=True)),
                ('amount_paid', models.TextField(blank=True)),
                ('amountpaid_date', models.TextField(blank=True)),
                ('nothing', models.TextField(blank=True)),
            ],
        ),
    ]
